# Code is referred from go-retryablehttp golang library
# Ref: https://github.com/hashicorp/go-retryablehttp/blob/main/.github/workflows/actionlint.yml

name: actionlint

on:
  push:
    paths:
      - .github/**

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - name: "Check GitHub workflow files"
        uses: docker://docker.mirror.hashicorp.services/rhysd/actionlint:latest
        with:
          args: -color
